#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py collectstatic --no-input
python manage.py runserver 0.0.0.0:8000 &
sleep 5
celery -A accounting_admin.tasks worker -l INFO