# Generated by Django 3.2.13 on 2023-12-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedsalary",
            name="try_to_save",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=24, verbose_name="try to save"
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="try_to_save",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=24, verbose_name="try to save"
            ),
        ),
    ]
