# Generated by Django 5.0.1 on 2024-01-15 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0003_remove_expectedsalary_user_remove_salary_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedsalary",
            name="deadline",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="expectedsalary",
            name="deadline_type",
            field=models.CharField(
                choices=[
                    ("first_business_day", "Primeiro dia útil"),
                    ("last_business_day", "Ultimo dia útil"),
                    ("fifth_business_day", "5° dia útil"),
                    ("fifteenth_business_day", "15° dia útil"),
                    ("date", "Data exata"),
                ],
                default="date",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
