# Generated by Django 3.2.13 on 2024-01-02 02:59
import django.core.validators
from django.db import migrations, models


def copy_deadline_data(apps, schema_editor):
    CreditCard = apps.get_model("credit_cards", "CreditCard")
    for credit_card in CreditCard.objects.all():
        credit_card.deadline_integer = (
            int(credit_card.deadline.day) if credit_card.deadline else 1
        )
        credit_card.save()


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="deadline_integer",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.RunPython(copy_deadline_data),
        migrations.RemoveField(
            model_name="creditcard",
            name="deadline",
        ),
        migrations.RenameField(
            model_name="creditcard",
            old_name="deadline_integer",
            new_name="deadline",
        ),
    ]
