# Generated by Django 3.2.13 on 2024-01-02 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0002_rename_deadline_creditcard_deadlines"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="closure",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
