# Generated by Django 5.0.1 on 2024-01-15 19:27

import django.db.models.deletion
from django.db import migrations, models


def set_account(apps, schema_editor):
    CreditCard = apps.get_model("credit_cards", "CreditCard")
    for credit_card in CreditCard.objects.all():
        credit_card.account_id = credit_card.user.accounts.last().account.uuid
        credit_card.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("banks", "0001_initial"),
        ("credit_cards", "0003_creditcard_closure"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_cards",
                to="accounts.account",
                verbose_name="account",
                null=True,
            ),
        ),
        migrations.RunPython(set_account),
        migrations.RemoveField(
            model_name="creditcard",
            name="user",
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_cards",
                to="banks.bank",
                verbose_name="bank",
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_cards",
                to="accounts.account",
                verbose_name="account",
            ),
        ),
    ]
