# Generated by Django 3.2.13 on 2023-12-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedexpense",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expectedexpense",
            name="deadline_type",
            field=models.CharField(
                choices=[
                    ("first_business_day", "Primeiro dia útil"),
                    ("last_business_day", "Ultimo dia útil"),
                    ("date", "Data exata"),
                ],
                default="date",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
