# Generated by Django 3.2.13 on 2023-12-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_auto_20231225_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedexpense",
            name="exists_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
