# Generated by Django 3.2.13 on 2023-12-30 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0001_initial"),
        ("expense", "0003_expectedexpense_exists_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedexpense",
            name="credit_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expected_expenses",
                to="credit_cards.creditcard",
                verbose_name="credit card",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="credit_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="credit_cards.creditcard",
                verbose_name="credit card",
            ),
        ),
    ]
