# Generated by Django 3.2.13 on 2024-01-01 23:47

from django.db import migrations, models


def copy_deadline_data(apps, schema_editor):
    MonthlyExpense = apps.get_model("expense", "monthlyexpense")
    for month in MonthlyExpense.objects.all():
        month.month_year = month.created_at.year
        month.save()


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0005_alter_expectedexpense_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyexpense",
            name="month_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="month_year"),
        ),
    ]
