# Generated by Django 3.2.13 on 2024-01-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0006_monthlyexpense_month_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expectedexpense",
            name="deadline_type",
            field=models.CharField(
                choices=[
                    ("first_business_day", "Primeiro dia útil"),
                    ("fifth_business_day", "5° dia útil"),
                    ("fifteenth_business_day", "15° dia útil"),
                    ("last_business_day", "Ultimo dia útil"),
                    ("date", "Data exata"),
                ],
                default="date",
                max_length=100,
            ),
        ),
    ]
