# Generated by Django 3.2.13 on 2024-01-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0003_creditcard_closure'),
        ('expense', '0007_alter_expectedexpense_deadline_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedexpense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_expenses', to='credit_cards.creditcard', verbose_name='credit card'),
        ),
        migrations.AlterField(
            model_name='expectedexpense',
            name='deadline_type',
            field=models.CharField(choices=[('first_business_day', 'Primeiro dia útil'), ('last_business_day', 'Ultimo dia útil'), ('fifth_business_day', '5° dia útil'), ('fifteenth_business_day', '15° dia útil'), ('date', 'Data exata')], default='date', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='credit_cards.creditcard', verbose_name='credit card'),
        ),
    ]
