# Generated by Django 5.0.1 on 2024-01-15 19:27

import django.db.models.deletion
from django.db import migrations, models


def set_account(apps, schema_editor):
    ExpectedExpense = apps.get_model("expense", "ExpectedExpense")
    Expense = apps.get_model("expense", "Expense")
    MonthlyExpense = apps.get_model("expense", "MonthlyExpense")

    for expected_expense in ExpectedExpense.objects.all():
        expected_expense.account_id = expected_expense.user.accounts.last().account.uuid
        expected_expense.save()

    for expense in Expense.objects.all():
        expense.account_id = expense.user.accounts.last().account.uuid
        expense.save()

    for monthly_expense in MonthlyExpense.objects.all():
        monthly_expense.account_id = monthly_expense.user.accounts.last().account.uuid
        monthly_expense.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("expense", "0008_auto_20240110_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedexpense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expected_expenses",
                to="accounts.account",
                verbose_name="account",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accounts.account",
                verbose_name="account",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyexpense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_expenses",
                to="accounts.account",
                verbose_name="account",
                null=True,
            ),
        ),
        migrations.RunPython(set_account),
        migrations.RemoveField(
            model_name="expectedexpense",
            name="user",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="user",
        ),
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="user",
        ),
        migrations.AlterField(
            model_name="expectedexpense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expected_expenses",
                to="accounts.account",
                verbose_name="account",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accounts.account",
                verbose_name="account",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyexpense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_expenses",
                to="accounts.account",
                verbose_name="account",
            ),
        ),
    ]
