# Generated by Django 3.2.13 on 2023-03-15 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedExpense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=24, verbose_name='value')),
                ('name', models.CharField(max_length=72, verbose_name='name')),
                ('description', models.CharField(max_length=144, verbose_name='description')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='is fixed')),
            ],
            options={
                'verbose_name': 'Expected Expense',
                'verbose_name_plural': 'Expected Expenses',
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('month', models.CharField(max_length=72, verbose_name='month')),
                ('total', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, verbose_name='total')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expenses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Monthly Expense',
                'verbose_name_plural': 'Monthly Expenses',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=24, verbose_name='value')),
                ('name', models.CharField(max_length=72, verbose_name='name')),
                ('description', models.CharField(max_length=144, verbose_name='description')),
                ('expected_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.expectedexpense', verbose_name='expected expense')),
                ('monthly_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.monthlyexpense', verbose_name='monthly expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.AddField(
            model_name='expectedexpense',
            name='monthly_expected_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_expenses', to='accounting.monthlyexpense', verbose_name='monthly expected expense'),
        ),
        migrations.AddField(
            model_name='expectedexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_expenses', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
