# Generated by Django 3.2.13 on 2023-12-11 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_expected_to_paid(apps, schema):
    Expense = apps.get_model("accounting", "Expense")

    for expense in Expense.objects.filter(expected_paid__isnull=False):
        expense.paid_value = expense.expected_paid.value
        expense.save()
        expense.expected_paid.delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0004_alter_salary_net"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="paid_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=24,
                null=True,
                verbose_name="value",
            ),
        ),
        migrations.RunPython(migrate_expected_to_paid),
        migrations.RemoveField(
            model_name="expense",
            name="expected_paid",
        ),
        migrations.AlterField(
            model_name="expectedexpense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expected_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="monthly_expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accounting.monthlyexpense",
                verbose_name="monthly expense",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyexpense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
