# Generated by Django 3.2.13 on 2023-12-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0005_auto_20231211_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="monthly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaries",
                to="accounting.monthlyexpense",
                verbose_name="monthly expense",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="paid_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=24,
                null=True,
                verbose_name="paid value",
            ),
        ),
    ]
