# Generated by Django 3.2.13 on 2023-12-14 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_auto_20231214_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedSalary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gross', models.DecimalField(decimal_places=6, default=0, max_digits=24, verbose_name='gross salary')),
                ('net', models.DecimalField(decimal_places=6, default=0, max_digits=24, verbose_name='net salary')),
                ('name', models.CharField(max_length=72, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_salaries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Expected Salary',
                'verbose_name_plural': 'Expected Salaries',
            },
        ),
    ]
