# Generated by Django 5.0.1 on 2024-01-15 19:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_users_accounts(apps, schema_editor):
    User = apps.get_model("users", "User")
    Account = apps.get_model("accounts", "Account")
    AccountSubscriber = apps.get_model("accounts", "AccountSubscriber")
    Bank = apps.get_model("banks", "Bank")

    default_bank = Bank.objects.last()
    accounts_objs = []
    account_subscriber_objs = []
    for user in User.objects.filter(is_superuser=False):
        account = Account(bank_id=default_bank.id)
        account_subscriber_objs.append(
            AccountSubscriber(user_id=user.id, account_id=account.id)
        )
        accounts_objs.append(account)
    Account.objects.bulk_create(accounts_objs)
    AccountSubscriber.objects.bulk_create(account_subscriber_objs)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("banks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=6, default=0, max_digits=24, verbose_name="total"
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="banks.bank",
                        verbose_name="bank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="AccountSubscriber",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="accounts.account",
                        verbose_name="bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Subscriber",
                "verbose_name_plural": "Account Subscribers",
            },
        ),
        migrations.RunPython(create_users_accounts),
    ]
