name: CI/CD Account Administrator

on:
  push:
    branches: [ "main" ]

jobs:
  # build-image-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image Backend
  #     run: |
  #       echo ${{ github.sha }}
  #       docker login -u  ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
  #       docker build -t lucasehonda/accounting_administrator_backend:${{ github.sha }} .
  #       docker push lucasehonda/accounting_administrator_backend:${{ github.sha }}
  # build-image-front:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image Frontend
  #     run: |
  #       echo ${{ github.sha }}
  #       docker login -u  ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
  #       cd frontend/accouting_admin
  #       docker build -t lucasehonda/accounting_administrator_frontend:${{ github.sha }} -f Dockerfile.react .
  #       docker push lucasehonda/accounting_administrator_frontend:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
    - name: Criar arquivo temporário para a chave privada
      run: |
        echo "${{ secrets.SSH_PRIVATY_KEY }}" > accountingAdmKey.pem
        sudo chmod 400 accountingAdmKey.pem
    - name: Create docker-compose
      run : |
        cd .envs/.prod/
        sed 's/{{DOCKER_TAG}}/${{ github.sha }}/g' docker-compose-base.yml > docker-compose.yml
        cat docker-compose.yml
    - name: instalar sshpass
      run: |
        ls 
        sudo apt-get update && sudo apt-get install -y sshpass && sudo apt install ssh
    - name: Run ssh
      run: ssh -i "accountingAdmKey.pem" -o StrictHostKeyChecking=no ubuntu@ec2-100-24-4-42.compute-1.amazonaws.com "ls"
        
    - name: sshpass usando sshpass
      run: |
        sshpass ssh -i "accountingAdmKey.pem" -o StrictHostKeyChecking=no ubuntu@ec2-100-24-4-42.compute-1.amazonaws.com "ls"


        
        
        
        







        
        
        
      

        
